org.gradle.jvmargs=-Xmx4096m -XX:+UseG1GC -XX:+ParallelRefProcEnabled -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
roborazzi.record.filePathStrategy=relativePathFromRoborazziContextOutputDirectory
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true
kotlin.incremental=true
ksp.incremental=true
kotlin.daemon.jvmoptions=-Xmx2048m -XX:+UseG1GC
